### ISSUE TITLE
sample code in C# for uploading media and looking for subjects

### ISSUE THREAD

**Issue by pmranade** [Cogniac/cogniac-sdk-csharp#1]
<img width="847" alt="screen shot 2018-01-25 at 11 29 15 am" src="https://user-images.githubusercontent.com/2286379/35408167-012abb74-01c3-11e8-98a1-4029771b3e8c.png">

**Comment by pmranade** [comment]
What we want the sample code to do is -
1. Get connection
2. create a set of known output_subjects which a media is going to be classified as
3. set the input_subject where the image will be associated to 
4. upload media
5. associate media to input subject
6. poll mediasubjects every x sec with y timeout
7. everytime you poll check whether the returned subject includes any subjects which are part of the output subjects defined at the beginning 
8. print when match is found

**Comment by alkadi** [comment]
In step #2, who provides the set of output_subjects? I'm assuming this is a known set of subjects.
In step #3, "input_subject" is provided here, correct? This is the subject we associate uploaded media with.

Polling is up to the client, it can be done in many ways. I don't know what type of application you are developing, a Windows Form? ASP.NET app? Console app? Polling methodology would depend on threading and how you are handling it (background, foreground, tasks or thread-pool). So if you want me to write that for you, please provide me with your application setup as such a sample wouldn't really be a part of the C# SDK.

The SDK can clearly do the following:

1) Upload a media, get a media ID.
2) Associate media with a given subject ID.
3) Get media-subjects associations and traverse the object to read subjects (object structure is in the documentation and is also in the API sample response provided by Cogniac).

The functionality is already in the SDK, it's not an issue.

**Comment by wskish** [comment]
customer is just looking for some more sample code to get them started.  assume just foreground polling for now.  yes outside sdk

**Comment by pmranade** [comment]
Step 2 - output_subjects can be retrieved from the app config. As the app_id is known it would be great to get the output_subjects from the app. 
Step 3 - yes this is the subject where the media is going to be associated by the user

**Comment by alkadi** [comment]
Thanks for a quick response, okay, so what is the issue?

Do you need help in developing a polling method? Or help traversing the SDK objects? Is it a console application? Or a Windows Form?

For step 2, if we can get the output subjects list from a given application, then an application ID must be provided. So can you list for me what are your inputs then?

**Comment by pmranade** [comment]
Inputs ==>
tenant_id, username, password -- can be in environment variable or in the script
media image filename
input_subject -- to associated the media

Outputs ==>
subject from media-subject call which matches the output_subjects

Its a sample code so we can assume its just a console app

**Comment by alkadi** [comment]
Ok, I'll give you a C# polling example soon, I'll upload it here.

**Comment by alkadi** [comment]
Here is a fully functional polling program, tested against my tenant.

To use:

1) Create a new Console application in Visual Studio 2017.
2) Open NuGet package manager, get the CSharp SDK 1.0.4.
3) Make sure you are working in "Release Mode".
4) Copy and paste the content of Program.cs OR replace Program.cs with the one in the zip.

[Program.zip](https://github.com/Cogniac/cogniac-sdk-csharp/files/1665842/Program.zip)

**Comment by pmranade** [comment]
Thanks Al for a quick response

**Comment by pmranade** [comment]
Quick question on this part of the code 
-------------------------------------------------------------
                                var listener = Task.Factory.StartNew(() =>
                                {
                                    while (true)
                                    {
                                        //poll media for output subjects every 5 seconds
                                        var mediaSubjects = con.GetMediaSubjects(mediaId);
                                        if (mediaSubjects != null)
                                        {
                                            // Traverse all the media subjects
                                            foreach (Datum d in mediaSubjects.Data)
                                            {
                                                // Check against our list of known output subjects
                                                // Acquired by application ID
                                                if (outputSubjects.Contains(d.Subject.SubjectUid))
                                                {
                                                    Console.WriteLine($"Media associated with output subject: {d.Subject.SubjectUid}");
                                                }
                                            }
                                        }
                                        Console.WriteLine("Polling...");
                                        Thread.Sleep(delay);                                                                   
                                        if (cancelToken.IsCancellationRequested)
                                        {
                                            // If canceled, kill task
                                            break;
                                        }
                                    }
                                    // Cleanup
                                }, cancelToken, TaskCreationOptions.LongRunning, TaskScheduler.Default);
-------------------------------------------------------------
Am I correct in understanding that cancelToken is sort of callback that happens when a matching subject is found which breaks the while loop??

**Comment by alkadi** [comment]
No, cancelToken is a semaphore to end the running polling thread. It's triggered when you call the cancel function right after the Console key input in my example file.

I hope this helps!

**Comment by pmranade** [comment]
Thanks
Then what would break the while loop when the matching subject is found? What we want is for the loop to be broken and subject to be printed if the matching subject is found in results of GetMediaSubjects --- Sorry if I am missing something very obvious not used to reading C# code

**Comment by alkadi** [comment]
No problem! Let me get to my computer and I'll draft a full explanation. I apologize for any delay.

**Comment by pmranade** [comment]
don't worry got it, thanks

**Comment by alkadi** [comment]
Should I mark this as resolved then?
