### ISSUE TITLE
Media download now requires API token to be passed

### ISSUE THREAD

**Issue by deepshikha-jha** [Cogniac/cogniac-sdk-csharp#10]
Downloading media now happens through public api vs directly through s3 buckets. This requires us to pass the API token

**Comment by alkadi** [comment]
The SDK isn't doing any downloading, it is only doing uploading, can you elaborate this issue? Maybe I am misunderstanding something.

**Comment by deepshikha-jha** [comment]
okay, this was if the sdk allowed for media download

**Comment by alkadi** [comment]
Ok, I have an uploading utility only, no downloading yet. I will close this for now, we can re-open it if we add downloading.
