### ISSUE TITLE
Implement media search functionality

### ISSUE THREAD

**Issue by deepshikha-jha** [Cogniac/cogniac-sdk-csharp#14]
https://cogniac.readme.io/docs/media-search

**Comment by alkadi** [comment]
@deepshikha-jha , does this return a standard media object array? As in this: https://cogniac.readme.io/docs/media or does it return a cut simplified media object with specific fields only? The example on the documentation site you provided shows it returning 1 media object only, is it safe to assume an array of objects if multiple media objects are found? Also, which parameters of the search query are optional and which are mandatory?

**Comment by deepshikha-jha** [comment]
yes it returns a standard media object array.
Also for the query parameters, it supports passing in of only one query param. So you can pass in either filename, or md5, or external_media_id, or domain_unit

**Comment by alkadi** [comment]
Thank you for the clarification @deepshikha-jha. I'll get working on it!

**Comment by alkadi** [comment]
Implemented in SDK 1.0.0.12, and will be in NuGet 1.0.13
