### ISSUE TITLE
remove reference to old token endpoint

### ISSUE THREAD

**Issue by wskish** [Cogniac/cogniac-sdk-csharp#15]
https://github.com/Cogniac/cogniac-sdk-csharp/blob/5a0c2c35d9e110bbd69312678e68473ad3a20f88/CogniacCSharpSDK/Connection.cs#L123

**Comment by alkadi** [comment]
Didn't you need to support both as per previous instructions?

**Comment by wskish** [comment]
we are deprecating the old one so want to transition everything over to the new one

**Comment by alkadi** [comment]
Fixed in SDK 1.0.0.11
