### ISSUE TITLE
allow user to specify consensus and probability when associating media to subject

### ISSUE THREAD

**Issue by deepshikha-jha** [Cogniac/cogniac-sdk-csharp#17]
Refer to python sdk associate_media function in subject.py
https://github.com/Cogniac/cogniac-sdk-py/blob/master/cogniac/subject.py

**Comment by deepshikha-jha** [comment]
1. User can send both consensus and uncal_prob to the API.
2. The 3 consensus values are 'True', 'False', 'None'
3. Default the consensus to 'None'
4. If the consensus is set to 'None' and the user does not send an uncal_prob, then default uncal_prob to 0.99
5. If the user sets the consensus to 'True' or 'False' ignore any uncal_prob that is set

**Comment by alkadi** [comment]
> 5.	If the user sets the consensus to 'True' or 'False' ignore any uncal_prob that is set

Does this mean we just don't upload the uncal_prob field at all when consensus is set to TRUE or FALSE?

**Comment by alkadi** [comment]
I already got the answer on Skype, thank you though! I will make this happen ASAP and push a new SDK out.

**Comment by alkadi** [comment]
Fixed in NuGet Package 1.0.11
