### ISSUE TITLE
re-authenticate upon token expiration without the user explicitly needing to create a new Cogniac Connection

### ISSUE THREAD

**Issue by ericsr** [Cogniac/cogniac-sdk-csharp#3]
There have also been some recent updates to the python SDK to automatically re-authenticate upon token expiration without the user explicitly needing to create a new Cogniac Connection.  I'm not sure if the C# sdk does this already (I'm guessing not) but it would be good to have it hide the re-authentication as well.

**Comment by alkadi** [comment]
Do you want this to be the default action? Or should there be an "auto re-authenticate" flag when the user establishes a connection for the first time? Such as:

Connection cc = new Connection("user", "pass", tenantId, autoRenew=true);

?

**Comment by ericsr** [comment]
@wskish Can you confirm this is what you want?

**Comment by alkadi** [comment]
Ok so I have implemented and tested this, the option is on by default unless the user specifically spawns a connection object with the autoRenewToken variable set to false.

**Comment by wskish** [comment]
sounds good

**Comment by alkadi** [comment]
Ok, awesome, I will push this change soon and then close this issue!

**Comment by alkadi** [comment]
Implemented in SDK version 1.0.0.6 / Nuget package 1.0.7
