### ISSUE TITLE
Support "synchronous API" for media detections

### ISSUE THREAD

**Issue by spatel-cog** [Cogniac/cogniac-sdk-csharp#4]
Update SDK to support synchronous API call in order to retrieve the results of a subject-media association. 

This requires adding a enable_wait flag when associating subjects to media and supporting retrieving detections with the resulting capture id.

Changes are in the "support_enable_wait" branch.

**Comment by alkadi** [comment]
It seems you have already implemented this, do you want me to merge the branch to master and test it? Please let me know!

**Comment by spatel-cog** [comment]
The changes in the branch should be integrated into master and verified.
Thanks.

**Comment by alkadi** [comment]
Ok, I will marge the branch onto master. I also noticed master has been forked and only the license was changed. Is that something needed? We can just change the license on master without the fork.

**Comment by deepshikha-jha** [comment]
Yes lets do that

**Comment by spatel-cog** [comment]
I tried to reuse the Converter from Common.cs to parse the output of MediaDetections - however, it appears that this converter need to be augmented to handle media detections: Here's a sample of the returned JSON:

{
   "other_media":[
   ],
   "detections":[
      {
         "model_id":null,
         "media_id":"M2XOJ3WCRKNHM7IMPIMACOYBF9DZ",
         "probability":0.9990004901712047,
         "created_at":1548970210.512554,
         "focus":null,
         "app_data_type":null,
         "inference_focus":null,
         "subject_uid":"buckeye_test_images_8hp",
         "app_data":null,
         "uncal_prob":null,
         "prev_prob":null,
         "detection_id":"HLQXGKUUCM:0",
         "user_id":"BCA@elbitsystems-us.com",
         "app_id":null,
         "activation":null
      },
      {
         "model_id":"Hpo-d-8e49-MrsAQbI7cwh4EgcF3B-YN-OW_mtsv1_INT_300.tgz",
         "media_id":"M2XOJ3WCRKNHM7IMPIMACOYBF9DZ",
         "probability":0.6785757541656494,
         "created_at":1548970210.998211,
         "focus":null,
         "app_data_type":"box_set",
         "inference_focus":null,
         "subject_uid":"buckeye_boxed_people_4vp",
         "app_data":[
            {
               "box":{
                  "y1":504,
                  "y0":167,
                  "x0":18,
                  "x1":449
               },
               "probability":0.6785757541656494
            },
            {
               "box":{
                  "y1":457,
                  "y0":178,
                  "x0":218,
                  "x1":822
               },
               "probability":0.6061137914657593
            },
            {
               "box":{
                  "y1":199,
                  "y0":29,
                  "x0":315,
                  "x1":470
               },
               "probability":0.4461803734302521
            },
            {
               "box":{
                  "y1":242,
                  "y0":22,
                  "x0":44,
                  "x1":146
               },
               "probability":0.4359453022480011
            },
            {
               "box":{
                  "y1":277,
                  "y0":0,
                  "x0":62,
                  "x1":322
               },
               "probability":0.3958449959754944
            }
         ],
         "uncal_prob":0.6785757541656494,
         "prev_prob":null,
         "detection_id":"LMRVGRMZNC:THVHJITYXG:HLQXGKUUCM:0",
         "user_id":null,
         "app_id":"0xrfDLdV",
         "activation":null
      },
{
         "model_id":"Hpo-i-8b48-UY3kb1ZC4TqxXptvCH-IN-v3_mtsv1_731.tgz",
         "media_id":"M2XOJ3WCRKNHM7IMPIMACOYBF9DZ",
         "probability":0.8906530681824439,
         "created_at":1548970210.734741,
         "focus":null,
         "app_data_type":null,
         "inference_focus":null,
         "subject_uid":"buckeye_ooi_frames_2qc",
         "app_data":null,
         "uncal_prob":0.9999043941497803,
         "prev_prob":null,
         "detection_id":"THVHJITYXG:HLQXGKUUCM:0",
         "user_id":null,
         "app_id":"ZNFCRxDI",
         "activation":null
      },
      {
         "model_id":"Hpo-i-8b48-AvvvqvNG2dil2ORDRO-IN-v3_mtsv1_12316.tgz",
         "media_id":"M2XOJ3WCRKNHM7IMPIMACOYBF9DZ",
         "probability":0.990956520226006,
         "created_at":1548970211.141156,
         "focus":{
            "box":{
               "y1":504,
               "y0":167,
               "x0":18,
               "x1":449
            }
         },
         "app_data_type":null,
         "inference_focus":null,
         "subject_uid":"conveyance_6nf",
         "app_data":null,
         "uncal_prob":1.0,
         "prev_prob":null,
         "detection_id":"WPXGCPONQF:LMRVGRMZNC:THVHJITYXG:HLQXGKUUCM:0",
         "user_id":null,
         "app_id":"az62EzMz",
         "activation":null
      },
  {
         "model_id":"Hpo-i-8b48-AvvvqvNG2dil2ORDRO-IN-v3_mtsv1_12316.tgz",
         "media_id":"M2XOJ3WCRKNHM7IMPIMACOYBF9DZ",
         "probability":0.9909543457352941,
         "created_at":1548970211.144183,
         "focus":{
            "box":{
               "y1":457,
               "y0":178,
               "x0":218,
               "x1":822
            }
         },
         "app_data_type":null,
         "inference_focus":null,
         "subject_uid":"conveyance_6nf",
         "app_data":null,
         "uncal_prob":0.9999997615814209,
         "prev_prob":null,
         "detection_id":"YBJBVWOAMV:LMRVGRMZNC:THVHJITYXG:HLQXGKUUCM:0",
         "user_id":null,
         "app_id":"az62EzMz",
         "activation":null
      }
   ],
   "media_list":[
      {
         "set_assignment":"training",
         "num_frames":null,
         "frame":null,
         "video":false,
         "frame_durations":[
         ],
         "duration":null,
         "size":201812.0,
         "video_context":null,
         "network_camera_id":null,
         "resize_urls":{
            "750":"https://elbit01.local.cogniac.io/downloadmedia/cogniac-media/M2XOJ3WCRKNHM7IMPIMACOYBF9DZ_max_750",
            "454":"https://elbit01.local.cogniac.io/downloadmedia/cogniac-media/M2XOJ3WCRKNHM7IMPIMACOYBF9DZ_max_454"
         },
         "original_url":null,
         "image_width":1008,
         "filename":"C:\\Cogniac\\Pics\\car_06.jpg",
         "original_landing_url":null,
         "fps":null,
         "uploaded_by_user":"BCA@elbitsystems-us.com",
         "media_timestamp":1548933685.0,
         "media_url":"https://elbit01.local.cogniac.io/downloadmedia/cogniac-media/M2XOJ3WCRKNHM7IMPIMACOYBF9DZ",
         "status":"success",
         "media_id":"M2XOJ3WCRKNHM7IMPIMACOYBF9DZ",
         "external_media_id":null,
         "time_base":null,
         "source_url":null,
         "author_profile_url":null,
         "media_src":"c_sharp_sdk",
         "parent_media_id":null,
         "md5":"6bc9f29f10421964e7696f91e6b63544",
         "parent_media_ids":[
         ],
         "meta_tags":null,
         "license":null,
         "tenant_id":"ebkd9ysrzk3f",
         "created_at":1548970206.600973,
         "author":null,
         "preview_url":null,
         "image_height":567,
         "media_format":"JPEG",
         "title":null
      }
   ]
}

**Comment by alkadi** [comment]
Yes, I will have to change the MediaDetections class. Will take care of it.

**Comment by alkadi** [comment]
I fixed the MediaDetections class and converter, however, what does it mean to "enable_wait". I can't find info about it in your API docs. (https://cogniac.readme.io/docs/subjects-media) 

Acquiring the MediaDetections from the received CaptureID right after the operation completes, shouldn't be an SDK job, this is the job for the user of the SDK.

Could you provide a python example of how this is working? I have the class fixed up, I can add the wait flag, but I need to test it to see what it does. Thanks!

**Comment by spatel-cog** [comment]
The documents do need updating. 
In the meanwhile, enable_wait is a mechanism to allow psuedo-synchronous response following subject-media association. The response from the media-detections api contains all detection outputs in across all models in a pipeline associated with the the capture_id.

The usage model is:
media_id = upload media()
capture_id = subject_media_association(media_id, input_subject, enable_wait=True)
detections = media_detections(media, capture_id)

The alternative model to get detections is to poll or configure the app(s) of interest with a URL to post detections.

**Comment by alkadi** [comment]
Yes, this has been implemented in main, I am testing it with @deepshikha-jha. There was a small error in the MediaDetections class and I believe it's now fixed. Just waiting to hear back.

**Comment by alkadi** [comment]
I believe this is now working and it will be in SDK version 1.0.8

**Comment by deepshikha-jha** [comment]
This looks like it has been fixed
