### ISSUE TITLE
Support /oauth/token and /token

### ISSUE THREAD

**Issue by spatel-cog** [Cogniac/cogniac-sdk-csharp#5]
A transition has been made use /token from oauth/token. Unfortunately, older systems which haven't had their software upgraded rely only support oauth/token.

The SDK should support both for now.

**Comment by alkadi** [comment]
So here we support both API-Key & the OAuth token for now, Correct?  So implementing #9  will also close this issue. I will need an API-Key for testing.

**Comment by deepshikha-jha** [comment]
This issue involved changing the API url from 'oauth/token' to just 'token'.

**Comment by alkadi** [comment]
Easy enough, will add both to the release SDK and check it in.

**Comment by alkadi** [comment]
So do you need me to take out the logic that I implemented before to track token expiration? And just re-new the token upon a 401?

**Comment by wskish** [comment]
We removed the expiration time from the return call since the token itself contains the definitive expiration time.  You can decode (no need to verify) the token with a JWT library and read the "exp" field to get the expiration time.

**Comment by alkadi** [comment]
Thanks for the information. I will implement that then.

**Comment by alkadi** [comment]
This is done, thanks @wskish I used JWT and it solved all the issues, it will be in SDK version 1.0.8, only the /token URL will be used, but the auth object will populate with all the data using the JWT decoder.
