### ISSUE TITLE
Support for configurable azure sas tokens

### ISSUE THREAD

**Issue by deepshikha-jha** [Cogniac/cogniac-sdk-csharp#7]

**Comment by alkadi** [comment]
Can you elaborate on this?

**Comment by deepshikha-jha** [comment]
https://github.com/Cogniac/cogniac-sdk-py/commit/ffef150362c3530bf1f08df1fe1d22b4a14530b8

**Comment by alkadi** [comment]
Ok so we just upload the token to the tenant, it isn't present in your API docs BTW: https://cogniac.readme.io/docs/tenants

**Comment by deepshikha-jha** [comment]
I will update the docs

**Comment by alkadi** [comment]
Thank you, please report back when you do.

**Comment by alkadi** [comment]
@deepshikha-jha any updates on the documentation? In the python code I see "azure_sas_tokens", does that mean it is an array of tokens? Any example usage you can share with me so I can implement this correctly? Thanks. My tenant doesn't have this field.

**Comment by alkadi** [comment]
Any updates here? @deepshikha-jha ?

**Comment by deepshikha-jha** [comment]
@wskish  any thoughts on this ?

**Comment by wskish** [comment]
It is currently just a list of tokens.  It would be better to have a more developed interface for crud ops on individual tokens but we started here with just a list for expediency.

**Comment by alkadi** [comment]
Thank you @wskish , so this is just a string field like the domain_unit for media, I can write any string value to it and read any string value from it, there is no validation process is there?

**Comment by alkadi** [comment]
Azure SAS Token and Tenant updating implemented in SDK 1.0.0.11 available in NuGet 1.0.12
